### ISSUE TITLE
Tailwind 2 compatibility issue

### ISSUE THREAD

**Issue by RedlicDev** [kartiknair/dhow#5]
Hi,
I want to install TailwindCSS 2 with the PostCSS plugin, but I have error:
`Error: [object Object] is not a PostCSS plugin`

I tried this https://tailwindcss.com/docs/installation#post-css-7-compatibility-build but still not working.

**Comment by kartiknair** [comment]
Sorry for the super late response, been busy with other things.

It does seem like Tailwind 2 depends on PostCSS v8 but thankfully the upgrade process was very smooth and did solve the problem. So `dhow@3.0.2` onwards now uses PostCSS 8 by default, keep this in mind for other plugins as well. See `examples/tailwind` for a Tailwind 2 enabled example or create one directly using:

```shell
npx create-dhow-app --template tailwind <app-name>
```

Thanks for opening the issue, I'm closing this for now. Feel free to reopen if you still face the same problem.
